<?php
$form = $this->form;
//$form->setAttribute('action', $this->url('project', array('action' => 'add')));
$form->prepare();
echo $this->form()->openTag($this->form);
echo $this->formRow($this->form->get('displayName'));
//echo $this->formRow($this->form->get('email'));
//echo $this->formRow($this->form->get('password'));
//echo $this->formRow($this->form->get('state'));
echo $this->formRow($this->form->get('submit'));
echo $this->form()->closeTag();