<?php
/**
 * Created by PhpStorm.
 * User: Фаил
 * Date: 07.11.13
 * Time: 21:26
 */

$title = 'Add new project';
$this->headTitle($title);
//print $this->showMessages();
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('project', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('body'));
echo $this->formRow($form->get('state'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();